# Generated by Django 3.0.2 on 2021-05-30 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docker',
            fields=[
                ('docker_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('algorithm_name', models.CharField(max_length=45)),
                ('create_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField()),
                ('memory_consumption', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('execution_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('institution', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('zip', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=45)),
                ('login_date', models.DateTimeField()),
                ('logout_date', models.DateTimeField()),
                ('dockers', models.ManyToManyField(to='myapi.Docker')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboardhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('docker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Docker')),
            ],
        ),
    ]
