# Generated by Django 3.2.5 on 2021-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_docker_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
