# Generated by Django 3.2.5 on 2021-07-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='execution_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='memory_consumption',
            field=models.FloatField(null=True),
        ),
    ]
